"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Field, Message, Modal } from "./ui";
export function Attachments({ portfolioId, journalId, files, enabled }: { portfolioId: string; journalId: string | null; files: { id: string; name: string; size: number }[]; enabled: boolean }) {
  const [error, setError] = useState(""), [pending, setPending] = useState(false), [deleting, setDeleting] = useState<string | null>(null);
  const router = useRouter();
  return <section className="panel space-y-5 p-6"><h2 className="text-sm font-medium">პირადი დანართები</h2><p className="text-xs leading-6 text-muted">PDF, PNG ან JPEG · მაქსიმუმ 2 მბ · 5 ფაილი თითო ჩანაწერზე</p>{files.map(f => <div key={f.id} className="flex items-center justify-between gap-3"><a href={`/api/attachments/${f.id}`} className="break-all text-xs text-brand">{f.name}</a><button className="text-xs text-negative" onClick={() => setDeleting(f.id)}>წაშლა</button></div>)}{enabled && journalId && files.length < 5 ? <form className="space-y-4" onSubmit={async e => { e.preventDefault(); const form = new FormData(e.currentTarget); form.set("portfolioId", portfolioId); form.set("journalId", journalId); setPending(true); setError(""); try { const response = await fetch("/api/attachments", { method: "POST", body: form }); if (!response.ok) { const body = await response.json(); setError(typeof body.error === "string" ? body.error : "ატვირთვა ვერ მოხერხდა."); } else router.refresh(); } catch { setError("ატვირთვა ვერ მოხერხდა."); } finally { setPending(false); } }}><Field label="ფაილის არჩევა"><input type="file" name="file" accept="application/pdf,image/png,image/jpeg" required /></Field><button className="button-secondary" disabled={pending}>{pending ? "იტვირთება…" : "დანართის ატვირთვა"}</button></form> : <p className="text-xs text-muted">{!enabled ? "დანართების საცავი ჯერ არ არის დაკავშირებული." : !journalId ? "დანართის დამატებამდე შეინახეთ ჟურნალი." : "დანართების მაქსიმალური რაოდენობა მიღწეულია."}</p>}{error && <Message error>{error}</Message>}<Modal open={deleting !== null} onOpenChange={v => { if (!v) setDeleting(null); }} title="დანართის წაშლა" description="ფაილი საცავიდან სამუდამოდ წაიშლება."><button className="button-danger" disabled={pending} onClick={async () => { setPending(true); try { const response = await fetch(`/api/attachments/${deleting}`, { method: "DELETE" }); if (!response.ok) setError("წაშლა ვერ მოხერხდა."); else { setDeleting(null); router.refresh(); } } catch { setError("წაშლა ვერ მოხერხდა."); } finally { setPending(false); } }}>წაშლა</button></Modal></section>;
}
