"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { ArrowLeftRight, Bell, BookOpen, ChartNoAxesCombined, ChevronDown, Command, Eye, FlaskConical, Gift, LayoutDashboard, Layers3, LineChart, Menu, PieChart, Route, Search, Settings2, X } from "lucide-react";
import { clsx } from "clsx";
import { useEffect, useMemo, useState } from "react";
import { Brand } from "./brand";
import { LogoutButton } from "./auth-buttons";
import { ThemeToggle } from "./theme-toggle";
import styles from "./shell-reference.module.css";

const pages = [["", "პორტფელი", LayoutDashboard], ["positions", "აქტივები", Layers3], ["analytics", "ანალიტიკა", ChartNoAxesCombined], ["watchlist", "დაკვირვება", Eye], ["journal", "ჩანაწერები", BookOpen], ["transactions", "ტრანზაქციები", ArrowLeftRight], ["statistics", "სტატისტიკა", LineChart], ["scenarios", "სცენარები", FlaskConical], ["allocation", "განაწილება", PieChart], ["strategy", "სტრატეგია", Route], ["airdrops", "Airdrops", Gift], ["settings", "პარამეტრები", Settings2]] as const;
const primary = new Set(["", "positions", "analytics", "watchlist", "journal"]);
export function Shell({ children, portfolios, userName }: { children: React.ReactNode; portfolios: { id: string; name: string }[]; userName: string }) {
  const pathname = usePathname(), router = useRouter();
  const [drawer, setDrawer] = useState(false), [commands, setCommands] = useState(false), [notifications, setNotifications] = useState(false), [query, setQuery] = useState("");
  const activeId = pathname.split("/")[2] ?? portfolios[0]?.id, base = `/portfolios/${activeId}`;
  const items = useMemo(() => pages.map(([segment, label, Icon]) => ({ segment, label, Icon, href: `${base}${segment ? `/${segment}` : ""}` })), [base]);
  const results = items.filter((item) => item.label.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  const active = (href: string) => pathname === href || href.endsWith("/positions") && pathname.startsWith(`${href}/`);
  useEffect(() => { const handle = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setCommands((open) => !open); } if (event.key === "Escape") setCommands(false); }; window.addEventListener("keydown", handle); return () => window.removeEventListener("keydown", handle); }, []);
  return <div className={styles.app}>
    <header className={styles.topbar}><div className={styles.brand}><Brand variant="topbar"/></div><nav className={styles.nav} aria-label="მთავარი ნავიგაცია">{items.filter((item) => primary.has(item.segment)).map((item) => <Link key={item.href} href={item.href} aria-current={active(item.href) ? "page" : undefined} className={clsx(styles.navLink, active(item.href) && styles.active)}>{item.label}</Link>)}</nav><div className={styles.tools}><button onClick={() => setDrawer(true)} className={clsx(styles.icon, styles.mobileMenu)} aria-label="მენიუს გახსნა"><Menu size={18}/></button><button onClick={() => setCommands(true)} className={styles.search} aria-label="ძიება"><Search size={16}/><span>მოძებნე აქტივი, გვერდი...</span><kbd>⌘ K</kbd></button><ThemeToggle/><button onClick={() => setNotifications((open) => !open)} className={styles.icon} aria-label="შეტყობინებები" aria-expanded={notifications}><Bell size={17}/><i className={styles.dot}/></button><span className={styles.avatar}>{userName.charAt(0)}</span><div className={styles.user}><select aria-label="პორტფელის არჩევა" value={activeId ?? ""} onChange={(event) => router.push(`/portfolios/${event.target.value}`)}>{portfolios.map((portfolio) => <option key={portfolio.id} value={portfolio.id}>{portfolio.name}</option>)}</select><span>{userName}</span></div><ChevronDown className={styles.chevron} size={14}/></div></header>
    <main id="main" className={styles.main}>{children}</main><footer className={styles.footer}><span>Crypto Collective X　© {new Date().getFullYear()}</span><span>თქვენი მონაცემები უსაფრთხოდაა დაცული.</span></footer>
    {drawer && <div className={styles.drawerBackdrop} onMouseDown={() => setDrawer(false)}><aside className={styles.drawer} onMouseDown={(event) => event.stopPropagation()}><div className={styles.drawerHeader}><Brand variant="topbar"/><button onClick={() => setDrawer(false)} aria-label="მენიუს დახურვა"><X size={18}/></button></div><nav>{items.map(({ href, label, Icon }) => <Link key={href} href={href} onClick={() => setDrawer(false)} className={active(href) ? styles.active : ""}><Icon size={18}/>{label}</Link>)}</nav><LogoutButton/></aside></div>}
    {notifications && <div className="notification-popover" role="dialog" aria-label="შეტყობინებები"><div><strong>შეტყობინებები</strong><button onClick={() => setNotifications(false)} aria-label="დახურვა"><X size={15}/></button></div><p>ყველა მაჩვენებელი განახლებულია.</p><small>ახალი შეტყობინებები არ არის.</small></div>}
    {commands && <div className="fixed inset-0 z-[70] grid place-items-start bg-black/60 px-4 pt-[12dvh] backdrop-blur-sm" onMouseDown={() => setCommands(false)}><div className="w-full max-w-xl overflow-hidden rounded-xl border border-[#2a3550] bg-[#101827]" role="dialog" aria-modal="true" aria-label="ბრძანებების ძიება" onMouseDown={(event) => event.stopPropagation()}><div className="flex items-center gap-3 border-b border-[#2a3550] px-4"><Command size={18} className="text-[#9aa8c1]"/><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="მოძებნეთ გვერდი ან მოქმედება..." className="border-0 bg-transparent px-0 py-4 text-sm shadow-none focus:outline-none"/><button onClick={() => setCommands(false)} className="text-[#9aa8c1]" aria-label="დახურვა"><X size={17}/></button></div><div className="max-h-[50dvh] overflow-y-auto p-2">{results.map(({ label, Icon, href }) => <button key={href} onClick={() => { router.push(href); setCommands(false); setQuery(""); }} className="flex w-full items-center gap-3 rounded-md px-3 py-2.5 text-left text-xs hover:bg-[#1a253b]"><Icon size={16} className="text-[#9aa8c1]"/>{label}</button>)}{!results.length && <p className="px-3 py-8 text-center text-xs text-[#9aa8c1]">შედეგი ვერ მოიძებნა.</p>}</div></div></div>}
  </div>;
}
export function PageHeading({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: React.ReactNode; action?: React.ReactNode }) { return <div className="mx-auto mb-8 flex max-w-[1608px] flex-wrap items-end justify-between gap-5 px-5 pt-7 sm:px-8"><div><p className="eyebrow mb-3">პორტფელი / {eyebrow}</p><h1 className="text-3xl font-semibold tracking-[-.045em] sm:text-[34px]">{title}</h1><div className="mt-2 max-w-2xl text-xs leading-6 text-muted">{description}</div></div>{action}</div>; }
